/**
 * {{ComponentName}} Component
 * Generated by Alpha Skills System
 */

import React, { useState{{#hasEffects}}, useEffect{{/hasEffects}} } from 'react';

interface {{ComponentName}}Props {
  {{#props}}
  {{name}}{{#optional}}?{{/optional}}: {{type}};
  {{/props}}
}

export const {{ComponentName}}: React.FC<{{ComponentName}}Props> = ({
  {{#props}}
  {{name}},
  {{/props}}
}) => {
  {{#hasState}}
  const [state, setState] = useState<{{stateType}}>({{initialState}});
  {{/hasState}}

  {{#hasEffects}}
  useEffect(() => {
    // Effect logic here
    {{effectLogic}}
  }, [{{effectDeps}}]);
  {{/hasEffects}}

  {{#hasHandlers}}
  const handle{{handlerName}} = ({{handlerParams}}) => {
    // Handler logic here
    {{handlerLogic}}
  };
  {{/hasHandlers}}

  return (
    <div className="{{className}}">
      <h2>{{heading}}</h2>
      {{#hasChildren}}
      <div className="{{className}}__content">
        {/* Component content */}
        {{children}}
      </div>
      {{/hasChildren}}
    </div>
  );
};

{{ComponentName}}.displayName = '{{ComponentName}}';
