/**
 * Unit Tests for {{moduleName}}
 * Generated by Alpha Skills System
 */

import { describe, it, expect{{#needsMocks}}, vi{{/needsMocks}} } from 'vitest';
import { {{importName}} } from '../{{modulePath}}';

describe('{{moduleName}}', () => {
  {{#tests}}
  it('{{description}}', {{async}}() => {
    // Arrange
    {{#setup}}
    {{.}}
    {{/setup}}

    {{#mocks}}
    const {{mockName}} = vi.fn().mockReturnValue({{mockReturn}});
    {{/mocks}}

    // Act
    {{#async}}await {{/async}}const result = {{#async}}await {{/async}}{{functionCall}};

    // Assert
    {{#assertions}}
    expect({{actual}}).{{matcher}}({{expected}});
    {{/assertions}}
  });

  {{/tests}}

  {{#hasErrorCases}}
  describe('Error Cases', () => {
    it('should handle {{errorCase}}', {{async}}() => {
      // Arrange
      {{errorSetup}}

      // Act & Assert
      {{#async}}await {{/async}}expect({{errorCall}}).{{#async}}rejects.{{/async}}toThrow({{errorMessage}});
    });
  });
  {{/hasErrorCases}}
});
