/**
 * {{description}}
 * Generated by Forge agent
 */

import { FastifyInstance, FastifyRequest, FastifyReply } from 'fastify';

interface {{RequestType}} {
  {{#requestFields}}
  {{name}}: {{type}};
  {{/requestFields}}
}

interface {{ResponseType}} {
  {{#responseFields}}
  {{name}}: {{type}};
  {{/responseFields}}
}

export async function {{handlerName}}(
  fastify: FastifyInstance
): Promise<void> {
  fastify.{{method}}('{{path}}', async (
    request: FastifyRequest<{ Body: {{RequestType}} }>,
    reply: FastifyReply
  ) => {
    try {
      // Extract request data
      const { {{#requestFields}}{{name}}{{^last}}, {{/last}}{{/requestFields}} } = request.body;

      // Validate input
      if (!{{#requestFields}}{{name}}{{^last}} || !{{/last}}{{/requestFields}}) {
        return reply.status(400).send({
          error: 'Missing required fields',
        });
      }

      // TODO: Implement business logic here
      {{#businessLogic}}
      {{line}}
      {{/businessLogic}}

      // Return success response
      const response: {{ResponseType}} = {
        {{#responseFields}}
        {{name}}: {{defaultValue}},
        {{/responseFields}}
      };

      return reply.send(response);
    } catch (error) {
      fastify.log.error(error);
      return reply.status(500).send({
        error: 'Internal server error',
      });
    }
  });
}
