/**
 * {{MiddlewareName}} Middleware
 * Generated by Alpha Skills System
 */

import { FastifyRequest, FastifyReply } from 'fastify';

export interface {{MiddlewareName}}Options {
  {{#options}}
  {{name}}: {{type}};
  {{/options}}
}

/**
 * {{description}}
 */
export async function {{middlewareName}}(
  request: FastifyRequest,
  reply: FastifyReply,
  options: {{MiddlewareName}}Options
): Promise<void> {
  {{#hasLogging}}
  request.log.info({ middleware: '{{middlewareName}}' }, '{{logMessage}}');
  {{/hasLogging}}

  try {
    {{#validations}}
    // Validation: {{validationDescription}}
    if ({{validationCondition}}) {
      return reply.status({{validationStatus}}).send({
        error: '{{validationMessage}}',
      });
    }
    {{/validations}}

    {{#hasProcessing}}
    // Processing logic
    {{processingLogic}}
    {{/hasProcessing}}

    {{#hasAttachments}}
    // Attach data to request
    request.{{attachmentName}} = {{attachmentValue}};
    {{/hasAttachments}}

    // Continue to next handler
  } catch (error) {
    request.log.error({ error, middleware: '{{middlewareName}}' }, 'Middleware error');
    return reply.status(500).send({
      error: 'Internal server error',
    });
  }
}
